name: Build for dev

on:
  push:
    branches: main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build
        env: 
          VUE_APP_EXAMPLE_API: ${{ secrets.APP_EXAMPLE_API }}

      - name: Upload production-ready build files
        uses: actions/upload-artifact@v3
        with:
          name: production-files
          path: ./dist

  copy:
    name: Copy to prod
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: production-files
          path: ./dist

      - name: Copy to production branch
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.PAT }}
          publish_dir: ./dist
          destination_dir: settings
          publish_branch: dev-build
          enable_jekyll: false
          keep_files: false
          commit_message: Build production code

  deploy:
    name: Deploy to dev
    needs: copy
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          script: |
            cd ${{ secrets.FOLDER }}
            git pull https://${{ secrets.PAT }}@github.com/fixedassetv2-fe/tsv2-mfe-boilerplate-app.git dev-build
